# Generated by Django 3.2.6 on 2021-08-15 07:08

import buku.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penulis', models.CharField(max_length=50)),
                ('tahun', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), buku.models.max_value_current_year])),
                ('sampul', models.ImageField(blank=True, null=True, upload_to='sampul/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.kategori')),
                ('penerbit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.penerbit')),
            ],
        ),
    ]
